services:
  dev:
    build:
      context: .
    command: sleep infinity
    depends_on:
      - cosmos
  cosmos:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    ports:
      - 8081